run:
  timeout: 5m

linters-settings:
  errcheck:
    # Ignore errors in test files and common patterns
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment # Too strict
      - shadow  # check-shadowing is deprecated

linters:
  enable:
    - errcheck
    - ineffassign
    - unused
    - gosimple
    - staticcheck
  disable:
    - gocyclo
    - goerr113
    - godox
    - gofmt
    - goimports
    - golint

issues:
  # Don't report unused fields in struct definitions for now
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true